//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public int Room_IDFK { get; set; }
        public int Guest_IDFK { get; set; }
        public int Charges_IDFK { get; set; }
        public System.DateTime Booking_From { get; set; }
        public System.DateTime Booking_To { get; set; }
        public bool Checked_In { get; set; }
    
        public virtual Charge Charge { get; set; }
        public virtual Guest_Info Guest_Info { get; set; }
        public virtual Room Room { get; set; }
    }
}
