//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Prices
    {
        public int Single_Price { get; set; }
        public int Double_Price { get; set; }
        public int Extra_Single_Price { get; set; }
        public int Extra_Double_Price { get; set; }
        public int Key { get; set; }
    }
}
